{
    "openapi": "3.0.0",
    "info": {
        "title": "ExampleSms API",
        "description": "This is a sample ExampleSms API server.  You can find out more about Swagger at",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "email": "apiteam@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8000/api/v1",
            "description": "ExampleSms API v1.0.0 server"
        }
    ],
    "paths": {
        "/login": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Login a user",
                "description": "Login a user",
                "operationId": "loginUser",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "username": "user234",
                                    "password": "password1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "boolean"
                                        }
                                    ]
                                },
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "success": true,
                                            "message": "User logged in successfully.",
                                            "data": {
                                                "name": "First Last",
                                                "email": "user@example.com",
                                                "username": "user234",
                                                "address": "1234 Main St",
                                                "phone": "1234567890"
                                            },
                                            "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzA1MTA0Njc3LCJleHAiOjE3MDUxMDgyNzcsIm5iZiI6MTcwNTEwNDY3NywianRpIjoiOGtTR1JLckRLYXFJaHlYbyIsInN1YiI6IjgiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.R_TzWgGlxPHY-tjIN1255GLWB7qdvRY9CZe39p2rixA",
                                            "token_type": "bearer",
                                            "expires_in": 3600
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "tags": [
                    "auth"
                ],
                "summary": "Adds a new user - with oneOf examples",
                "description": "Adds a new user",
                "operationId": "addUser",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "password_confirmation": {
                                        "type": "string"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "phone": {
                                        "oneOf": [
                                            {
                                                "type": "string"
                                            },
                                            {
                                                "type": "integer"
                                            }
                                        ]
                                    },
                                    "address": {
                                        "oneOf": [
                                            {
                                                "type": "string"
                                            },
                                            {
                                                "type": "integer"
                                            }
                                        ]
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "username": "user234",
                                    "email": "user@example.com",
                                    "password": "password1",
                                    "password_confirmation": "password1",
                                    "name": "First Last",
                                    "phone": "1234567890",
                                    "address": "1234 Main St"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "boolean"
                                        }
                                    ]
                                },
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "success": true,
                                            "message": "The user named First Last was successfully created",
                                            "status": "201",
                                            "statusText": "Created"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/sms-report": {
            "get": {
                "tags": [
                    "sms"
                ],
                "summary": "SMS Report",
                "description": "SMS report endpoint.",
                "operationId": "reportSms",
                "parameters": [
                    {
                        "name": "start_date",
                        "in": "query",
                        "description": "Start date",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "format": "date",
                            "example": "2021-01-01"
                        }
                    },
                    {
                        "name": "end_date",
                        "in": "query",
                        "description": "End date",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "format": "date",
                            "example": "2021-01-01"
                        }
                    },
                    {
                        "name": "status",
                        "in": "query",
                        "description": "Status",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "format": "string",
                            "enum": [
                                "pending",
                                "delivered",
                                "failed"
                            ]
                        }
                    },
                    {
                        "name": "sort_by",
                        "in": "query",
                        "description": "Sort by",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "format": "string",
                            "enum": [
                                "user_id",
                                "phone",
                                "send_time"
                            ]
                        }
                    },
                    {
                        "name": "sort_direction",
                        "in": "query",
                        "description": "Sort direction",
                        "required": false,
                        "schema": {
                            "type": "string",
                            "format": "string",
                            "enum": [
                                "asc",
                                "desc"
                            ]
                        }
                    },
                    {
                        "name": "page",
                        "in": "query",
                        "description": "Page number",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "format": "integer",
                            "example": "1"
                        }
                    },
                    {
                        "name": "per_page",
                        "in": "query",
                        "description": "Number of items per page",
                        "required": false,
                        "schema": {
                            "type": "integer",
                            "format": "integer",
                            "example": "10"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "The SMS list has been fetched successfully."
                                        },
                                        "data": {
                                            "type": "object",
                                            "example": "{\n     *     'id': 1,\n     *     'phone': '905555555555',\n     *     'message': 'Hello World',\n     *     'origin': 'SMS',\n     *     'status': 'delivered',\n     *     'request': {\n     *     rquestData\n     *      },\n     *     'response': {\n     *     responseData\n     *     },\n     *     'send_time': '2021-01-01 00:00:00',\n     *     'request_time': '2021-01-01 00:00:00',\n     *     }"
                                        },
                                        "meta": {
                                            "type": "object",
                                            "example": "{\n     *     'total': 1,\n     *     'per_page': 10,\n     *     'current_page': 1,\n     *     'last_page': 1,\n     *     'from': 1,\n     *     'to': 1,\n     *     }"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "false"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "SMS List not found."
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/sms-report-detail": {
            "get": {
                "tags": [
                    "sms"
                ],
                "summary": "SMS Report Detail",
                "description": "SMS report detail endpoint.",
                "operationId": "reportSmsDetail",
                "parameters": [
                    {
                        "name": "id",
                        "in": "query",
                        "description": "SMS ID",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "integer",
                            "example": "1"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "SMS found."
                                        },
                                        "data": {
                                            "type": "object",
                                            "example": "{\n     * 'id': 1,\n     * 'phone': '905555555555',\n     * 'message': 'Hello World',\n     * 'origin': 'SMS',\n     * 'status': 'delivered',\n     * 'request': {\n     * rquestData\n     * },\n     * 'response': {\n     * responseData\n     * },\n     * 'send_time': '2021-01-01 00:00:00',\n     * 'request_time': '2021-01-01 00:00:00',\n     * }"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "false"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "SMS not found."
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/send-sms": {
            "post": {
                "tags": [
                    "sms"
                ],
                "summary": "Send SMS",
                "description": "Send SMS endpoint.",
                "operationId": "sendSms",
                "parameters": [
                    {
                        "name": "phone",
                        "in": "query",
                        "description": "Phone number",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "string",
                            "example": "905*********"
                        }
                    },
                    {
                        "name": "origin",
                        "in": "query",
                        "description": "SMS Sender",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "string",
                            "example": "SMS Sender"
                        }
                    },
                    {
                        "name": "message",
                        "in": "query",
                        "description": "SMS Message",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "string",
                            "example": "This is message."
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "oneOf": [
                                        {
                                            "type": "boolean"
                                        }
                                    ]
                                },
                                "examples": {
                                    "result": {
                                        "summary": "An result object.",
                                        "value": {
                                            "success": true,
                                            "message": "User logged in successfully.",
                                            "data": {
                                                "name": "First Last",
                                                "email": "user@example.com",
                                                "username": "user234",
                                                "address": "1234 Main St",
                                                "phone": "1234567890"
                                            },
                                            "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL3YxL2xvZ2luIiwiaWF0IjoxNzA1MTA0Njc3LCJleHAiOjE3MDUxMDgyNzcsIm5iZiI6MTcwNTEwNDY3NywianRpIjoiOGtTR1JLckRLYXFJaHlYbyIsInN1YiI6IjgiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.R_TzWgGlxPHY-tjIN1255GLWB7qdvRY9CZe39p2rixA",
                                            "token_type": "bearer",
                                            "expires_in": 3600
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    },
    "tags": [
        {
            "name": "auth",
            "description": "Operations about auth"
        },
        {
            "name": "sms",
            "description": "Operations about report"
        }
    ]
}